version: "3.9"

services:
  php:
    container_name: php
    build:
      context: './php'
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html
    ports:
      - "80:80"
#  node:

#    image: node
#    container_name: nodejs
##    build:
##      context: './node'
##      dockerfile: Dockerfile
#    command:
#      - node app.js
#    volumes:
#      - ./src/:/var/www/html





#
#
#networks:
#  my_network:
#    driver: bridge